### ISSUE TITLE
Administración - Proveedores : Actualizar proveedor

### ISSUE THREAD

**Issue by comodoro180** [comodoro180/acot#15]
En el momento de actualizar un proveedor se presenta un error debido a que el código de la ciudad no es correcto. 

Se presenta el siguiente mensaje de error:
"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`acot_desa`.`tproveedor`, CONSTRAINT `TPROVEEDOR_fk0` FOREIGN KEY (`IDCIUDAD`) REFERENCES `tciudad` (`IDCIUDAD`))"

**Comment by Soto1311** [comment]
Solucionado
