### ISSUE TITLE
Login - validar correo electrónico

### ISSUE THREAD

**Issue by comodoro180** [comodoro180/acot#22]
Se debe almacenar y validar el correo electrónico en minúsculas. Esto evita que no sea sensible a mayusculas o minusculas.

- [ ] Ajustes en recuperar contraseña
- [ ] Ajustar login
- [ ] Admin usuarios

**Comment by Soto1311** [comment]
Solucionado

**Comment by comodoro180** [comment]
@comodoro180 se debe validar esta solución

**Comment by comodoro180** [comment]
Se  hizo uso de la función strtolower();
